/**
 * @license
 * Copyright Google LLC All Rights Reserved.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://angular.io/license
 */
import {ConstantPool, outputAst as o, R3PartialDeclaration} from '@angular/compiler';

import {AstObject} from '../../ast/ast_value';

/**
 * A definition generated by a `PartialLinker`, ready to emit.
 *
 * 由 `PartialLinker` 生成的定义，可以发出了。
 *
 */
export interface LinkedDefinition {
  expression: o.Expression;
  statements: o.Statement[];
}

/**
 * An interface for classes that can link partial declarations into full definitions.
 *
 * 可以将部分声明链接为完整定义的类的接口。
 *
 */
export interface PartialLinker<TExpression> {
  /**
   * Link the partial declaration `metaObj` information to generate a full definition expression.
   *
   * 链接部分声明的 `metaObj` 信息以生成完整的定义表达式。
   *
   * @param metaObj An object that fits one of the `R3DeclareDirectiveMetadata` or
   *     `R3DeclareComponentMetadata` interfaces.
   *
   * 适合 `R3DeclareDirectiveMetadata` 或 `R3DeclareComponentMetadata` 接口之一的对象。
   *
   */
  linkPartialDeclaration(
      constantPool: ConstantPool,
      metaObj: AstObject<R3PartialDeclaration, TExpression>): LinkedDefinition;
}
